### ISSUE TITLE
SSL error on Windows when calling rforcecom.query

### ISSUE THREAD

**Issue by springml** [hiratake55/RForcecom#28]
I am getting the below error when calling rforcecom.query function:

```
Error in function (type, msg, asError = TRUE)  : 
  error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
```

On Linux I had to use the following option to get around this issue.  But this does not seem to work in Windows.  Any ideas?

```
options(RCurlOptions = list(sslversion=1))
```

**Comment by ReportMort** [comment]
I found a SO thread (http://stackoverflow.com/questions/30202666/https-sslv3-alert-handshake-failure-from-geturl) that seemed to have your same error message, where the solution was to set `ssl_cipher_list="RC4-SHA"`, like this:
```
options(RCurlOptions = list(ssl_cipher_list="RC4-SHA"))

# this will list all possible RCurl options that you might want to configure:
listCurlOptions()
```

In the past I've used `ssl.verifypeer=FALSE` as a workaround in the past, so that might also be worth a shot. This thread on SO also seems relevant at first glance: http://stackoverflow.com/questions/6736895/using-rcurl-with-https

**Comment by springml** [comment]
Many thanks for the links.  The gist seems to be that the server does not support sslv3 so setting sslversion=1 forces use of TLS protocol.  That worked on Linux but for some reason does not work in RStudio on Windows.  But this is obviously specific to my environment and nothing to do with the package.  Closing.
