### ISSUE TITLE
Unable to login: TLS 1.0 has been disabled in this organization. Please use TLS 1.1 or higher when connecting to Salesforce using https.

### ISSUE THREAD

**Issue by akananth1729** [hiratake55/RForcecom#42]
Recently, our organization upgraded from TLS 1.0 to TLS 1.1 in Salesforce. Ever since then, I've been getting the following error message when I use the rforcecom.login() function:

UNSUPPORTED_CLIENT: TLS 1.0 has been disabled in this organization. Please use TLS 1.1 or higher when connecting to Salesforce using https.

Our org has a lot of very sensitive data that we send in and out of our Salesforce instance, so we would not want to disable the TLS 1.1 requirement. Is there a version of RForcecom that complies with TLS 1.1? 

Thanks!
Aparna

**Comment by ampu3ro** [comment]
Apparently [this issue](https://help.salesforce.com/apex/HTViewSolution?id=000221207) is not specific to your organization. I also encountered it and spent most of my morning trying to figure out solutions. I don't really know anything about encryption protocols but I think the problem is related to the SSL/TLS version RCurl supports.

@hiratake55 converting all the `RCurl::curlPerform` calls to `httr::VERB` seemed to do the trick for me. I'm guessing httr has more updated certificates or something like that.

Hope it helps!

**Comment by ReportMort** [comment]
Yes, seems like a good time to upgrade to `xml2` and `httr`. 

@ampu3ro Did you convert all the functions in the package? If so and if you don't mind submitting that as pull request, then that would be awesome. Even a simple link to a branch of your own for others to install from would be nice. Otherwise, I'll start migrating.

**Comment by ampu3ro** [comment]
I have a package I built for my company that does most of the same things but evolved from a time before I knew anything about packages or even pull requests. Unfortunately now it seems a bit late to merge. Sorry about that

**Comment by hiratake55** [comment]
@akananth1729 @ampu3ro @ReportMort Thank you very much for your important report. I also have checked TLS error happens on my side after activating the administration settings. I will check the workaround.

**Comment by hiratake55** [comment]
@akananth1729 @ampu3ro @ReportMort  I've changed all functions using RCurl to httr. I will upload the newest version to CRAN tomorrow. Please notify me If there are still problems remains. Thank you for notifying me the issue!

**Comment by JoshuaNorvell** [comment]
Can you please remove me from the mailing list?

--------------------------------------------
On Thu, 6/30/16, Takekatsu Hiramura <notifications@github.com> wrote:

 Subject: Re: [hiratake55/RForcecom] Unable to login: TLS 1.0 has been disabled in this organization. Please use TLS 1.1 or higher when connecting to Salesforce using https. (#42)
 To: "hiratake55/RForcecom" <RForcecom@noreply.github.com>
 Date: Thursday, June 30, 2016, 8:48 AM
 
 @akananth1729 @ampu3ro
 @ReportMort  I've changed all functions using RCurl to
 httr. I will upload the newest version to CRAN tomorrow.
 Please notify me If there are still problems remains. Thank
 you for notifying me the issue!
 
 ---
 You are receiving this because you are subscribed to this
 thread.

**Comment by ReportMort** [comment]
@JoshuaNorvell - Are you not able to unsubscribe from the thread using button on right hand side of screen?

![image](https://cloud.githubusercontent.com/assets/5299737/16504873/216fe6ba-3ee8-11e6-8157-fc23aebbe6c1.png)

**Comment by ReportMort** [comment]
@hiratake55 Thanks for making the fix so quickly.

**Comment by JoshuaNorvell** [comment]
No 😐 
--------------------------------------------
On Thu, 6/30/16, Steve Mortimer <notifications@github.com> wrote:

 Subject: Re: [hiratake55/RForcecom] Unable to login: TLS 1.0 has been disabled in this organization. Please use TLS 1.1 or higher when connecting to Salesforce using https. (#42)
 To: "hiratake55/RForcecom" <RForcecom@noreply.github.com>
 Cc: "Joshua Norvell - Data Analyst" <joshuanorvell@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Thursday, June 30, 2016, 2:32 PM
 
 @JoshuaNorvell - Are you not able to
 unsubscribe from the thread using button on right hand side
 of screen?
 
 ![image](https://cloud.githubusercontent.com/assets/5299737/16504873/216fe6ba-3ee8-11e6-8157-fc23aebbe6c1.png)
 
 
 ---

**Comment by hiratake55** [comment]
@JoshuaNorvell Please do change your settings or unwatch the project. Thanks.

![gh1](https://cloud.githubusercontent.com/assets/101812/16508904/929c4718-3f72-11e6-9260-bbb0f5191b3f.PNG)

![gh2](https://cloud.githubusercontent.com/assets/101812/16508905/929e317c-3f72-11e6-9d76-7cbc15f85dfe.PNG)

**Comment by hiratake55** [comment]
@akananth1729 @ampu3ro @ReportMort On CRAN now.

**Comment by JoshuaNorvell** [comment]
Can I please be removed from this list? Thanks. 
--------------------------------------------
On Fri, 7/1/16, Takekatsu Hiramura <notifications@github.com> wrote:

 Subject: Re: [hiratake55/RForcecom] Unable to login: TLS 1.0 has been disabled in this organization. Please use TLS 1.1 or higher when connecting to Salesforce using https. (#42)
 To: "hiratake55/RForcecom" <RForcecom@noreply.github.com>
 Cc: "Joshua Norvell - Data Analyst" <joshuanorvell@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Friday, July 1, 2016, 3:02 AM
 
 @akananth1729 @ampu3ro @ReportMort On CRAN
 now.
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by hiratake55** [comment]
@JoshuaNorvell Unfortunately, I can't remove your account from my side, could you kindly do remove from watch list by yourself. This is an only way to do this. Thanks.
